baseURL = ""
languageCode = "en-us"
title = "narrativesaw"

disableKinds = ["taxonomy", "taxonomyTerm"]

[Author]  
  name = "Li-Heng Hsu" 
  email = "yesleon@me.com"
  
[permalinks]
  pages = "/:filename.md"