baseURL = ""
languageCode = "en-us"
title = "narrativesaw"
googleAnalytics = "UA-136672120-1"

[Author]  
  name = "Li-Heng Hsu" 
  email = "yesleon@me.com"
  
[permalinks]
  short-stories = "/short-stories/:filename.md"
  others = "/others/:filename.md"
  
[taxonomies]
  tag = "tags"