baseURL = ""
languageCode = "en-us"
title = "narrativesaw"

[Author]  
  name = "Li-Heng Hsu" 
  email = "yesleon@me.com"
  
[permalinks]
  pages = "/pages/:filename.md"
  
[taxonomies]
  category = "categories"
  tag = "tags"